name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-release:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v5
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Get Tag Name
      id: get_data
      shell: bash
      run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
    - name: Make Nix
      if: matrix.os != 'windows-latest'
      working-directory: ./Source
      run: make
      shell: bash
    - name: Make WIN
      if: matrix.os == 'windows-latest'
      working-directory: ./Source
      run: nmake
    - name: Package NIX
      if: matrix.os != 'windows-latest'
      run: |
        zip --junk-paths merlin32.zip Source/merlin32 README.md
    - name: Package WIN
      if: matrix.os == 'windows-latest'
      run: |
        copy Source\merlin32.exe merlin32.exe
        7z.exe a merlin32.zip merlin32.exe README.md
    - name: Rename Asset
      shell: bash
      run: mv merlin32.zip merlin32-${{ matrix.os }}-${{ steps.get_data.outputs.SOURCE_TAG }}.zip
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_data.outputs.SOURCE_TAG }}
        name: Release ${{ steps.get_data.outputs.SOURCE_TAG }}
        files: merlin32-${{ matrix.os }}-${{ steps.get_data.outputs.SOURCE_TAG }}.zip
        draft: false
        prerelease: false
